[package]
name = "triboferrin"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.53", features = ["derive"] }
figment = { version = "0.10.19", features = [ "env", "toml" ] }
serde = { version = "1.0.228", features = ["derive"] }
